name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on push to the main branch
  pull_request:
    branches:
      - main  # Trigger pipeline on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate HTML
        run: |
          sudo apt-get install -y tidy
          tidy -q -e index.html

      - name: Validate CSS
        run: |
          sudo npm install -g csslint
          csslint styles.css

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
